# Generated by Django 5.2 on 2025-04-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
