# Generated by Django 5.2 on 2025-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='APIKey',
            field=models.TextField(null=True, unique=True),
        ),
    ]
