# Generated by Django 5.2 on 2025-04-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_app', '0006_remove_character_money_alter_character_user'),
        ('item_app', '0004_rename_minus_one_buy_item_yesterday_buy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='character_app.character')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_point', models.IntegerField()),
                ('buy_point', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_app.item')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='watchlist_items', to='watchlist_app.watchlist')),
            ],
        ),
    ]
