# Generated by Django 5.2 on 2025-04-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='Character',
            new_name='character',
        ),
    ]
