# Generated by Django 5.2 on 2025-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_rename_character_watchlist_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist_item',
            name='buy_point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watchlist_item',
            name='sell_point',
            field=models.IntegerField(null=True),
        ),
    ]
