# Generated by Django 5.2 on 2025-04-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rarity', models.TextField()),
                ('vendor_value', models.IntegerField()),
                ('game_id', models.IntegerField()),
                ('icon', models.URLField()),
                ('today_buy', models.IntegerField(null=True)),
                ('minus_one_buy', models.IntegerField(null=True)),
                ('minus_three_buy', models.IntegerField(null=True)),
                ('today_sell', models.IntegerField(null=True)),
                ('minus_one_sell', models.IntegerField(null=True)),
                ('minus_three_sell', models.IntegerField(null=True)),
            ],
        ),
    ]
