# Generated by Django 5.2 on 2025-04-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0003_item_character'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='minus_one_buy',
            new_name='yesterday_buy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='minus_one_sell',
            new_name='yesterday_sell',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='minus_three_buy',
            new_name='yesteryesterday_buy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='minus_three_sell',
            new_name='yesteryesterday_sell',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='today_buy',
            new_name='yesteryesteryesterday_buy',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='today_sell',
            new_name='yesteryesteryesterday_sell',
        ),
        migrations.RemoveField(
            model_name='item',
            name='prices_updated',
        ),
    ]
